version: "2"
services:
    jekyll-ci:
        build: .
        command: bash -c "bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000"
        volumes:
            - ../:/opt/tiger/XwindBlog
        working_dir: /opt/tiger/XwindBlog
        ports:
            - "4000:4000"
